mutation UpdateCustomerData($id: uuid!, $address: String!, $name: String!, $phone: String!) {
  update_customers_by_pk(pk_columns: { id: $id }, _set: { address: $address, name: $name, phone: $phone }) {
    id
    address
    name
    phone
  }
}
